"""your migration message

Revision ID: 9932c1c9877b
Revises: 140fa19714be
Create Date: 2025-01-07 15:29:54.314076

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9932c1c9877b'
down_revision: Union[str, None] = '140fa19714be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('testObj', sa.Column('img', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('testObj', 'img')
    # ### end Alembic commands ###
